<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>An Evolutionary Analysis of Industrial Entrepreneurship and R&amp;D Resources in Turkiye – Burcu A.’s Analytics Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Burcu A.’s Analytics Lab</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./posts.html"> 
<span class="menu-text">My Posts</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-emu660-coursework" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">EMU660 Coursework</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-emu660-coursework">    
        <li>
    <a class="dropdown-item" href="./assignments.html">
 <span class="dropdown-text">Assignments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./project.html">
 <span class="dropdown-text">Project</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://emu-hacettepe-analytics.github.io/emu660-spring2025-burcualtunoglu/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/in/burcu-altunoğlu-355613173/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-linkedin"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#project-overview-and-scope" id="toc-project-overview-and-scope" class="nav-link active" data-scroll-target="#project-overview-and-scope">1. Project Overview and Scope</a>
  <ul class="collapse">
  <li><a href="#problem-definition" id="toc-problem-definition" class="nav-link" data-scroll-target="#problem-definition"><strong><em>Problem Definition</em></strong></a></li>
  <li><a href="#research-objectives" id="toc-research-objectives" class="nav-link" data-scroll-target="#research-objectives"><strong><em>Research Objectives</em></strong></a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">2. Data</a>
  <ul class="collapse">
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source">2.1 Data Source</a></li>
  <li><a href="#general-information-about-data" id="toc-general-information-about-data" class="nav-link" data-scroll-target="#general-information-about-data">2.2 General Information About Data</a>
  <ul class="collapse">
  <li><a href="#industrial-total-enterprise-count-data" id="toc-industrial-total-enterprise-count-data" class="nav-link" data-scroll-target="#industrial-total-enterprise-count-data"><em>Industrial Total Enterprise Count Data</em></a></li>
  <li><a href="#rd-activities-data-of-industrial-and-service-enterprises" id="toc-rd-activities-data-of-industrial-and-service-enterprises" class="nav-link" data-scroll-target="#rd-activities-data-of-industrial-and-service-enterprises"><em>R&amp;D Activities Data of Industrial and Service Enterprises</em></a></li>
  </ul></li>
  <li><a href="#reason-of-choice" id="toc-reason-of-choice" class="nav-link" data-scroll-target="#reason-of-choice">2.3 Reason of Choice</a></li>
  <li><a href="#preprocessing" id="toc-preprocessing" class="nav-link" data-scroll-target="#preprocessing">2.4 Preprocessing</a>
  <ul class="collapse">
  <li><a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import"><strong><em>Data Import</em></strong></a></li>
  <li><a href="#variable-selection-and-disaggregation" id="toc-variable-selection-and-disaggregation" class="nav-link" data-scroll-target="#variable-selection-and-disaggregation"><strong><em>Variable Selection and Disaggregation</em></strong></a></li>
  <li><a href="#temporal-alignment-and-data-merging" id="toc-temporal-alignment-and-data-merging" class="nav-link" data-scroll-target="#temporal-alignment-and-data-merging"><strong><em>Temporal Alignment and Data Merging</em></strong></a></li>
  <li><a href="#handling-of-missing-observations" id="toc-handling-of-missing-observations" class="nav-link" data-scroll-target="#handling-of-missing-observations"><strong><em>Handling of Missing Observations</em></strong></a></li>
  <li><a href="#persistent-data-storage" id="toc-persistent-data-storage" class="nav-link" data-scroll-target="#persistent-data-storage"><strong><em>Persistent Data Storage</em></strong></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">3. Analysis</a>
  <ul class="collapse">
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">3.1 Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#correlation-analysis" id="toc-correlation-analysis" class="nav-link" data-scroll-target="#correlation-analysis">Correlation Analysis</a></li>
  </ul></li>
  <li><a href="#trend-analysis" id="toc-trend-analysis" class="nav-link" data-scroll-target="#trend-analysis">3.2 Trend Analysis</a>
  <ul class="collapse">
  <li><a href="#model-summaries-and-interpretation" id="toc-model-summaries-and-interpretation" class="nav-link" data-scroll-target="#model-summaries-and-interpretation">Model Summaries and Interpretation</a></li>
  <li><a href="#general-assessment" id="toc-general-assessment" class="nav-link" data-scroll-target="#general-assessment">General Assessment</a></li>
  </ul></li>
  <li><a href="#model-fitting" id="toc-model-fitting" class="nav-link" data-scroll-target="#model-fitting">3.3 Model Fitting</a>
  <ul class="collapse">
  <li><a href="#multivariate-linear-regression-analysis" id="toc-multivariate-linear-regression-analysis" class="nav-link" data-scroll-target="#multivariate-linear-regression-analysis">Multivariate Linear Regression Analysis</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">3.4 Results</a></li>
  </ul></li>
  <li><a href="#results-and-key-takeaways" id="toc-results-and-key-takeaways" class="nav-link" data-scroll-target="#results-and-key-takeaways">4. Results and Key Takeaways</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">An Evolutionary Analysis of Industrial Entrepreneurship and R&amp;D Resources in Turkiye</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="burcu-altunoğlu---mustafa-erdem-bakir" class="level4">
<h4 class="anchored" data-anchor-id="burcu-altunoğlu---mustafa-erdem-bakir"><strong><em>Burcu ALTUNOĞLU - Mustafa Erdem BAKIR</em></strong></h4>
</section>
<section id="project-overview-and-scope" class="level1">
<h1>1. Project Overview and Scope</h1>
<section id="problem-definition" class="level3">
<h3 class="anchored" data-anchor-id="problem-definition"><strong><em>Problem Definition</em></strong></h3>
<p>The growth of entrepreneurial activities in the industrial sector is a dynamic factor that influences not only economic development but also scientific productivity and technological capacity. Evaluating how changes in the number of industrial enterprises affect the composition and size of the R&amp;D workforce is of strategic importance for understanding the development of innovation capacity.</p>
<p>In this context, the primary research question of the project is defined as follows:</p>
<p>What is the impact of changes in the number of industrial enterprises in Turkiye on the educational level and gender distribution of R&amp;D personnel between 2009 and 2022?</p>
<p>In addressing this question, the analysis will not only consider the total number of R&amp;D personnel, but also account for variations in their educational attainment and gender composition.</p>
</section>
<section id="research-objectives" class="level3">
<h3 class="anchored" data-anchor-id="research-objectives"><strong><em>Research Objectives</em></strong></h3>
<p>The primary objectives of this study are as follows:</p>
<ul>
<li><p>To conduct a comparative analysis of the evolution of the number of industrial enterprises in Turkiye with the educational and gender composition of the R&amp;D workforce over time,</p></li>
<li><p>To identify statistically significant and structural relationships among these variables,</p></li>
<li><p>To estimate the effects of entrepreneurial activities on the composition of the R&amp;D workforce through a multiple linear regression model,</p></li>
<li><p>To develop policy recommendations for Turkiye’s science and technology agenda and industrial strategies based on the findings.</p></li>
</ul>
</section>
</section>
<section id="data" class="level1">
<h1>2. Data</h1>
<p>The datasets used in this study consist of comprehensive, large-scale statistical data published annually by the TÜİK, the official statistical agency of Turkiye. Both datasets provide sufficient numerical scope for analysis and allow for meaningful comparisons across both temporal and spatial dimensions.</p>
<section id="data-source" class="level2">
<h2 class="anchored" data-anchor-id="data-source">2.1 Data Source</h2>
<p>TÜİK Official Data Portal: https://data.tuik.gov.tr/</p>
<p>The raw data analyzed in this project were obtained from files downloaded from the TURKSTAT data portal, provided in .xlsx format. The relevant files will be included as source materials on the project’s GitHub page.</p>
</section>
<section id="general-information-about-data" class="level2">
<h2 class="anchored" data-anchor-id="general-information-about-data">2.2 General Information About Data</h2>
<section id="industrial-total-enterprise-count-data" class="level3">
<h3 class="anchored" data-anchor-id="industrial-total-enterprise-count-data"><em>Industrial Total Enterprise Count Data</em></h3>
<p>This dataset contains annual figures on the total number of industrial enterprises operating at both national and provincial levels across Turkiye. Available since 2009, it provides a quantitative foundation for monitoring the dynamics of entrepreneurship in the industrial sector.</p>
</section>
<section id="rd-activities-data-of-industrial-and-service-enterprises" class="level3">
<h3 class="anchored" data-anchor-id="rd-activities-data-of-industrial-and-service-enterprises"><em>R&amp;D Activities Data of Industrial and Service Enterprises</em></h3>
<p>The R&amp;D dataset comprises annual statistics on research and development (R&amp;D) activities conducted by industrial and service enterprises in Turkiye. Regularly published since 2003, the dataset reports the total number of R&amp;D personnel nationwide and classifies this workforce by educational attainment (e.g., doctorate, master’s, bachelor’s degrees) and employment status. As such, it offers rich content in terms of both quantitative magnitude and qualitative detail.</p>
<p>When considered together, these two datasets enable a relational analysis of entrepreneurial capacity and scientific human capital in Turkiye. Their time-series structure also makes them suitable for modeling and forecasting applications. In particular, the national-level coverage of R&amp;D personnel data, combined with the availability of industrial enterprise counts at both the national and provincial levels, ensures a high degree of representativeness for national-level analysis.</p>
</section>
</section>
<section id="reason-of-choice" class="level2">
<h2 class="anchored" data-anchor-id="reason-of-choice">2.3 Reason of Choice</h2>
<p>Both datasets have been obtained from up-to-date, publicly available, and reliable sources provided by the TÜİK. The fact that these datasets are published within the context of Turkiye allows this study to contribute as a decision-support tool for policy-making at the national level. Moreover, their time-series structure enables multidimensional statistical analyses.</p>
<p>In this regard, the selected datasets are well-suited for generating analytical insights within the scope of industrial engineering, particularly in the areas of decision support systems, resource allocation optimization, technology management, and sustainable development.</p>
</section>
<section id="preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="preprocessing">2.4 Preprocessing</h2>
<p>The two main datasets used in this project were obtained from the official portal of the TÜİK in .xlsx format. These datasets are published annually at the national level and cover the number of industrial enterprises as well as the qualitative and demographic characteristics of R&amp;D personnel. Although the data are structured, several preprocessing steps are required to make them ready for analysis.</p>
<p>The data import and preprocessing workflow will follow these systematic steps:</p>
<section id="data-import" class="level3">
<h3 class="anchored" data-anchor-id="data-import"><strong><em>Data Import</em></strong></h3>
<p>The data files will be imported into the R environment using packages such as readxl, dplyr, and tidyr. During this process, the original data structure will be preserved while transforming the datasets into a format that is both reorganizable and suitable for analysis.</p>
</section>
<section id="variable-selection-and-disaggregation" class="level3">
<h3 class="anchored" data-anchor-id="variable-selection-and-disaggregation"><strong><em>Variable Selection and Disaggregation</em></strong></h3>
<section id="industrial-enterprise-data" class="level4">
<h4 class="anchored" data-anchor-id="industrial-enterprise-data"><strong>Industrial Enterprise Data:</strong></h4>
<p>This dataset presents the annual number of industrial enterprises across Turkiye’s 81 provinces. For the purposes of this project, only the total number of industrial enterprises at the national level will be used. This choice ensures analytical consistency, as the R&amp;D dataset is also provided at the national level.</p>
</section>
<section id="rd-personnel-data-by-educational-level" class="level4">
<h4 class="anchored" data-anchor-id="rd-personnel-data-by-educational-level"><strong>R&amp;D Personnel Data (by Educational Level):</strong></h4>
<p>The number of R&amp;D personnel is disaggregated by educational attainment (e.g., Doctorate or higher, Master’s, Bachelor’s, Associate degree, and Other). In this study, the trends for each educational category will be analyzed independently over time, and their relationship with the number of industrial enterprises will be examined.</p>
</section>
<section id="rd-personnel-data-by-gender" class="level4">
<h4 class="anchored" data-anchor-id="rd-personnel-data-by-gender"><strong>R&amp;D Personnel Data (by Gender):</strong></h4>
<p>The dataset also includes total counts of male and female R&amp;D personnel. This demographic distinction enables gender-based analysis of employment in the scientific workforce. Accordingly, the relationship between industrial entrepreneurial capacity and gender-based scientific employment will be evaluated.</p>
</section>
</section>
<section id="temporal-alignment-and-data-merging" class="level3">
<h3 class="anchored" data-anchor-id="temporal-alignment-and-data-merging"><strong><em>Temporal Alignment and Data Merging</em></strong></h3>
<p>Although both datasets are published on an annual basis, they may differ in terms of the specific years they cover. Therefore, only the overlapping period from 2009 to 2022 will be included in the analysis. All variables—namely the number of industrial enterprises, R&amp;D personnel by educational level, and R&amp;D personnel by gender—will be merged based on a common year variable to construct a unified multivariate data frame.</p>
</section>
<section id="handling-of-missing-observations" class="level3">
<h3 class="anchored" data-anchor-id="handling-of-missing-observations"><strong><em>Handling of Missing Observations</em></strong></h3>
<p>Observations with missing values will be marked as NA during the analysis process. Depending on the analytical technique applied, these cases will either be excluded or analyzed separately using the available (non-missing) portions of the data. In the presence of missing values, the reliability of the model outcomes will be assessed with particular attention.</p>
</section>
<section id="persistent-data-storage" class="level3">
<h3 class="anchored" data-anchor-id="persistent-data-storage"><strong><em>Persistent Data Storage</em></strong></h3>
<p>After the data preprocessing procedures are completed, the resulting unified data frame will be saved in .RData format and made accessible via the project’s GitHub repository. This practice ensures the reproducibility of the analytical process and aligns with the principles of open science.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gerekli paketler</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Gerekli paketler</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Girişim verisinin okunması</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>girisim_data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi-toplam girisim sayisi.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"report2"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>girisim_data<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(girisim_data<span class="sc">$</span>Year)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Ar-Ge verisinin okunması</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>arge_data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi Hizmet Kuruluslari ArGe Faaliyetleri.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"Sheet0"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Eğitim düzeyine göre verinin düzenlenmesi</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>arge_egitim <span class="ot">&lt;-</span> arge_data <span class="sc">%&gt;%</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">Education level</span><span class="st">`</span>, Year, Number) <span class="sc">%&gt;%</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Education_Level =</span> <span class="st">`</span><span class="at">Education level</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">Year =</span> <span class="fu">as.integer</span>(Year),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Number =</span> <span class="fu">as.numeric</span>(Number)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Education_Level), <span class="sc">!</span><span class="fu">is.na</span>(Year), Year <span class="sc">&gt;=</span> <span class="dv">2009</span>, Year <span class="sc">&lt;=</span> <span class="dv">2022</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>arge_egitim_wide <span class="ot">&lt;-</span> arge_egitim <span class="sc">%&gt;%</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> Education_Level,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> Number,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fn =</span> sum,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fill =</span> <span class="dv">0</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Cinsiyete göre verinin düzenlenmesi</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>arge_gender <span class="ot">&lt;-</span> arge_data <span class="sc">%&gt;%</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Gender, Year, Number) <span class="sc">%&gt;%</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">Year =</span> <span class="fu">as.integer</span>(Year),</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">Number =</span> <span class="fu">as.numeric</span>(Number),</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">Gender =</span> <span class="fu">str_trim</span>(Gender)</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Gender), <span class="sc">!</span><span class="fu">is.na</span>(Year), Year <span class="sc">&gt;=</span> <span class="dv">2009</span>, Year <span class="sc">&lt;=</span> <span class="dv">2022</span>)</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>arge_cinsiyet_wide <span class="ot">&lt;-</span> arge_gender <span class="sc">%&gt;%</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> Gender,</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> Number,</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fn =</span> sum,</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fill =</span> <span class="dv">0</span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Verilerin birleştirilmesi</span></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>veri_birlesik <span class="ot">&lt;-</span> girisim_data <span class="sc">%&gt;%</span></span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(arge_egitim_wide, <span class="at">by =</span> <span class="st">"Year"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(arge_cinsiyet_wide, <span class="at">by =</span> <span class="st">"Year"</span>)</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a><span class="co"># Kaydet</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(veri_birlesik, <span class="at">file =</span> <span class="st">"veri_birlesik_egitim_cinsiyet.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>With this structure, the project will enable a detailed statistical investigation of the following relationships during the analysis phase:</p>
<ul>
<li><p>The relationship between the number of industrial enterprises and the educational level of the R&amp;D workforce,</p></li>
<li><p>The relationship between the number of industrial enterprises and the gender distribution (female/male ratio) of R&amp;D personnel.</p></li>
</ul>
</section>
</section>
</section>
<section id="analysis" class="level1">
<h1>3. Analysis</h1>
<p><br>
The two datasets used in this project consist of quantitative variables that are well-suited for time-series analysis in terms of both content and structure. The key features of these datasets are summarized below:</p>
<p>Industrial Enterprise Data contains the annual total number of industrial enterprises operating across Turkiye. For example, in 2009, the number of active enterprises nationwide was recorded at approximately 3.2 million. The data are published regularly on a yearly basis and provide a macro-level representation of the dynamics of the industrial sector.</p>
<p>R&amp;D Data includes the annual number of R&amp;D personnel employed by industrial and service sector enterprises across Turkiye. The distribution of this variable over the years ranges approximately from 10,000 to 40,000 individuals. Given that R&amp;D personnel data directly reflect scientific capacity, the variable holds strategic importance.</p>
<p>Both variables are quantitative and structured in a yearly time-series format. This structure allows for the application of both visual and model-based analytical techniques.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(veri_birlesik, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> <span class="st">`</span><span class="at">Total Number of Enterprises</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Total Number of Industrial Enterprises Over Time"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Enterprises"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure shows a steady upward trend in the total number of industrial enterprises in Turkiye between 2009 and 2022. The growth, which was limited in the 2009-2015 period, gained momentum after 2016; a significant increase was observed especially between 2020-2021. This rapid rise can be attributed to the transformation in production structures and digitalization during the pandemic period. However, the stagnation in 2022 points to the impact of market saturation or macroeconomic constraints. Overall, there is a quantitative growth in industrial entrepreneurship, but the sustainability and qualitative effects of this growth should be evaluated separately.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Required packages</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the Excel file</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi Hizmet Kuruluslari ArGe Faaliyetleri.xlsx"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter between 2009 and 2023</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>df_filtered <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2009</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2023</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by Year and Education Level</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>df_grouped <span class="ot">&lt;-</span> df_filtered <span class="sc">%&gt;%</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, <span class="st">`</span><span class="at">Education level</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total =</span> <span class="fu">sum</span>(Number, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_grouped, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Total, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">`</span><span class="at">Education level</span><span class="st">`</span>, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of R&amp;D Personnel by Education Level (2009–2023)"</span>,</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Personnel"</span></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>An analysis of the distribution of R&amp;D personnel in Turkiye by educational level between 2009 and 2023 reveals that the number of bachelor’s degree graduates is by far the highest and has been increasing rapidly over the years. While there is also an increase in the number of master’s and associate’s degree graduates, it is noteworthy that the number of personnel with a doctorate degree and above remains relatively limited. This indicates that there is an increasing need for highly qualified human resources in R&amp;D activities, but this need has not yet been adequately met. While the proportion of high school graduates tends to decrease over time, the number of personnel in the “other” category fluctuates. In general, it can be said that there is a transformation in the R&amp;D personnel structure towards higher levels of education.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Excel dosyasını oku</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi Hizmet Kuruluslari ArGe Faaliyetleri.xlsx"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 2009–2023 filtrele</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>df_filtered <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2009</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2023</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Cinsiyete göre yıllık toplam</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>df_gender <span class="ot">&lt;-</span> df_filtered <span class="sc">%&gt;%</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Gender) <span class="sc">%&gt;%</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total =</span> <span class="fu">sum</span>(Number, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafik</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_gender, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Total, <span class="at">color =</span> Gender, <span class="at">group =</span> Gender)) <span class="sc">+</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of R&amp;D Personnel by Gender (2009–2023)"</span>,</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Personnel"</span>,</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Gender"</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>An analysis of the distribution of personnel employed in R&amp;D in Turkiye between 2009 and 2023 by gender shows that the number of male personnel increased steadily every year, reaching over 135,000 by 2023. The number of female personnel has shown a similar upward trend; however, this increase has been more limited compared to men, reaching approximately 60,000 in 2023. This indicates that a gender-based imbalance persists in the R&amp;D sector.</p>
<p>It is noteworthy that the increase in the number of female personnel gained momentum especially after 2016. This increase shows that women’s participation in R&amp;D activities has strengthened and that there has been a positive development in terms of gender equality. However, the current picture reveals the need for more comprehensive and sustainable policies to increase the representation of women in R&amp;D.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Excel dosyasını oku</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi Hizmet Kuruluslari ArGe Faaliyetleri.xlsx"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 2009–2023 filtrele</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>df_filtered <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2009</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2023</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Cinsiyet bazında yıllık toplamlar</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>df_gender <span class="ot">&lt;-</span> df_filtered <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Gender) <span class="sc">%&gt;%</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total =</span> <span class="fu">sum</span>(Number, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Gender, <span class="at">values_from =</span> Total)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Sütun adlarını düzelt</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_gender) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Year"</span>, <span class="st">"Female"</span>, <span class="st">"Male"</span>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Kadın oranını hesapla</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>df_gender <span class="ot">&lt;-</span> df_gender <span class="sc">%&gt;%</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Female_Ratio =</span> Female <span class="sc">/</span> (Female <span class="sc">+</span> Male) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>df_gender<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(df_gender<span class="sc">$</span>Year)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Geliştirilmiş grafik</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_gender, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Female_Ratio, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#C51B7D"</span>, <span class="at">linewidth =</span> <span class="fl">1.5</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>) <span class="sc">+</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#C51B7D"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">stroke =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="dv">1</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">30</span>)) <span class="sc">+</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">2009</span>, <span class="dv">2023</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Female Share in R&amp;D Personnel</span><span class="sc">\n</span><span class="st">(2009–2023)"</span>,</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Female Share (%)"</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"gray30"</span>),</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Between 2009 and 2023, the ratio of female employees in the R&amp;D sector in Turkiye increased steadily. From 21.5% in 2009, the proportion of female employees increased to 27.8% by 2023. This increase shows that women’s participation in R&amp;D activities is strengthening and that there is a positive trend towards gender equality. However, the ratio is still below 30%, indicating that policies to increase the representation of women in R&amp;D need to be sustained and further supported.</p>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">3.1 Exploratory Data Analysis</h2>
<section id="correlation-analysis" class="level3">
<h3 class="anchored" data-anchor-id="correlation-analysis">Correlation Analysis</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the Excel files</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>enterprises <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi-toplam girisim sayisi.xlsx"</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>rd <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi Hizmet Kuruluslari ArGe Faaliyetleri.xlsx"</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for the years 2009–2023</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>enterprises <span class="ot">&lt;-</span> enterprises <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2009</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2023</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>rd <span class="ot">&lt;-</span> rd <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2009</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2023</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>rd<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(rd<span class="sc">$</span>Year)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>enterprises<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(enterprises<span class="sc">$</span>Year)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Proceed with merging</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>merged <span class="ot">&lt;-</span> rd <span class="sc">%&gt;%</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(enterprises, <span class="at">by =</span> <span class="st">"Year"</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize R&amp;D personnel by education level and year</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>education_summary <span class="ot">&lt;-</span> merged <span class="sc">%&gt;%</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, <span class="st">`</span><span class="at">Education level</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total =</span> <span class="fu">sum</span>(Number, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">`</span><span class="at">Education level</span><span class="st">`</span>, <span class="at">values_from =</span> Total)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge with enterprise numbers</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>correlation_data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(education_summary, enterprises, <span class="at">by =</span> <span class="st">"Year"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Enterprises =</span> <span class="st">`</span><span class="at">Total Number of Enterprises</span><span class="st">`</span>)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Pearson correlation analysis</span></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>education_vars <span class="ot">&lt;-</span> <span class="fu">names</span>(correlation_data)[<span class="sc">!</span>(<span class="fu">names</span>(correlation_data) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Year"</span>, <span class="st">"Enterprises"</span>))]</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (var <span class="cf">in</span> education_vars) {</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>  test_data <span class="ot">&lt;-</span> correlation_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(Enterprises, <span class="fu">all_of</span>(var)) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>()</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(test_data) <span class="sc">&gt;=</span> <span class="dv">3</span>) {</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>    result <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(test_data[[<span class="dv">1</span>]], test_data[[<span class="dv">2</span>]], <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"----"</span>, var, <span class="st">"----</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Pearson Correlation Coefficient (r):"</span>, <span class="fu">round</span>(result<span class="sc">$</span>estimate, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"p-value:"</span>, <span class="fu">signif</span>(result<span class="sc">$</span>p.value, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"----"</span>, var, <span class="st">"----</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Insufficient data: correlation test could not be performed.</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>---- Associate Degree ----
Pearson Correlation Coefficient (r): 0.97 
p-value: 8.872e-10 

---- Bachelor's Degree ----
Pearson Correlation Coefficient (r): 1 
p-value: 6.472e-15 

---- Doctorate or Higher ----
Pearson Correlation Coefficient (r): 0.96 
p-value: 1.119e-08 

---- High School ----
Pearson Correlation Coefficient (r): 0.94 
p-value: 1.441e-07 

---- Master's Degree ----
Pearson Correlation Coefficient (r): 0.98 
p-value: 3.001e-11 

---- Other ----
Pearson Correlation Coefficient (r): -0.87 
p-value: 2.649e-05 </code></pre>
</div>
</div>
<p>Positive and strong correlation coefficients are observed for all education levels (except “Other”). In particular, there is an almost perfect linear relationship between bachelor’s degree graduates (r = 1.00, p &lt; 0.001) and the number of industrial enterprises. This suggests that the number of R&amp;D personnel employed at the bachelor’s level increases systematically with the increase in the number of enterprises. Similarly, master’s (r = 0.98) and associate degree (r = 0.97) graduates also exhibit very strong and highly statistically significant relationships. Strong positive correlations are also obtained for PhD and high school graduates (r = 0.96 and r = 0.94, respectively), suggesting that industrial development generally increases the demand for R&amp;D personnel from all educational levels.</p>
<p>The notable exception is the category “Other”. A negative correlation coefficient (r = -0.87, p &lt; 0.001) was calculated in this group. This suggests that the number of staff with “Other” educational attainment decreases as the number of enterprises increases, suggesting that industrialization has pushed this group of staff out of the system or that employment patterns have changed. This result suggests that the definitions of education level should be clarified and the transformation in this group should be examined in detail.</p>
</section>
</section>
<section id="trend-analysis" class="level2">
<h2 class="anchored" data-anchor-id="trend-analysis">3.2 Trend Analysis</h2>
<p>The relationship between the number of industrial enterprises and the employment of R&amp;D personnel at different educational levels between 2009 and 2023 in Turkiye is analyzed. First of all, Pearson correlation analysis was used to determine the linear relationships between the number of industrial enterprises and the number of R&amp;D personnel, and the direction, strength and statistical significance of these relationships were evaluated. According to the results obtained, it has been determined that the number of personnel at “Bachelor’s Degree”, “Master’s Degree”, “Associate Degree”, “Doctorate or Higher” and “High School” levels show highly positive and statistically significant relationships with the number of industrial enterprises.</p>
<p>In line with these findings, simple linear regression analyses were conducted for these five education levels. With these analyses, the effect of the increase in the number of industrial enterprises on the number of R&amp;D personnel at the relevant level was modeled and the significance and fitting power of the model were evaluated by calculating basic parameters such as slope coefficient, constant term, p-value, R² and F-statistic for each regression model. In addition, the trends are supported by graphs that visually present the regression lines and data points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gerekli kütüphaneler</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Verileri oku</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>enterprises <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi-toplam girisim sayisi.xlsx"</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>rd <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi Hizmet Kuruluslari ArGe Faaliyetleri.xlsx"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Yıl düzelt</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>enterprises<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(enterprises<span class="sc">$</span>Year)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>rd<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(rd<span class="sc">$</span>Year)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Yıl filtrele</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>enterprises <span class="ot">&lt;-</span> enterprises <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2009</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2023</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>rd <span class="ot">&lt;-</span> rd <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2009</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2023</span>)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Eğitim düzeyine göre özet</span></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>education_summary <span class="ot">&lt;-</span> rd <span class="sc">%&gt;%</span></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, <span class="st">`</span><span class="at">Education level</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total =</span> <span class="fu">sum</span>(Number, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">`</span><span class="at">Education level</span><span class="st">`</span>, <span class="at">values_from =</span> Total)</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Birleştir</span></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>df_regression <span class="ot">&lt;-</span> <span class="fu">left_join</span>(education_summary, enterprises, <span class="at">by =</span> <span class="st">"Year"</span>)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Eğitim seviyeleri</span></span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>education_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bachelor's Degree"</span>,</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Master's Degree"</span>,</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Associate Degree"</span>,</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Doctorate or Higher"</span>,</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>  <span class="st">"High School"</span></span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>output_lines <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (level <span class="cf">in</span> education_levels) {</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Model kur</span></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>  formula_text <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste0</span>(<span class="st">"`"</span>, level, <span class="st">"` ~ `Total Number of Enterprises`"</span>))</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>  model <span class="ot">&lt;-</span> <span class="fu">lm</span>(formula_text, <span class="at">data =</span> df_regression)</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>  summary_out <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Değerleri al</span></span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>  intercept <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">coef</span>(model)[<span class="dv">1</span>], <span class="dv">2</span>)</span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>  slope <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">coef</span>(model)[<span class="dv">2</span>], <span class="dv">5</span>)</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>  r2 <span class="ot">&lt;-</span> <span class="fu">round</span>(summary_out<span class="sc">$</span>r.squared, <span class="dv">4</span>)</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>  pval <span class="ot">&lt;-</span> <span class="fu">formatC</span>(summary_out<span class="sc">$</span>coefficients[<span class="dv">2</span>, <span class="dv">4</span>], <span class="at">format =</span> <span class="st">"e"</span>, <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>  fstat <span class="ot">&lt;-</span> <span class="fu">round</span>(summary_out<span class="sc">$</span>fstatistic[<span class="dv">1</span>], <span class="dv">2</span>)</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Metinleri oluştur</span></span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>  section <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">strrep</span>(<span class="st">"="</span>, <span class="dv">50</span>)),</span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"Regression Summary for: %s"</span>, level),</span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>    <span class="fu">strrep</span>(<span class="st">"="</span>, <span class="dv">50</span>),</span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%-20s: %12s"</span>, <span class="st">"Intercept (β₀)"</span>, intercept),</span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%-20s: %12s"</span>, <span class="st">"Slope (β₁)"</span>, slope),</span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%-20s: %12s"</span>, <span class="st">"R²"</span>, r2),</span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%-20s: %12s"</span>, <span class="st">"p-value (slope)"</span>, pval),</span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%-20s: %12s"</span>, <span class="st">"F-statistic"</span>, fstat)</span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a>  output_lines <span class="ot">&lt;-</span> <span class="fu">c</span>(output_lines, section)</span>
<span id="cb12-66"><a href="#cb12-66" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-67"><a href="#cb12-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-68"><a href="#cb12-68" aria-hidden="true" tabindex="-1"></a><span class="co"># Hepsini tek seferde bastır</span></span>
<span id="cb12-69"><a href="#cb12-69" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste</span>(output_lines, <span class="at">collapse =</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
==================================================
Regression Summary for: Bachelor's Degree
==================================================
Intercept (β₀)   :    -233577.2
Slope (β₁)       :      0.07888
R²                 :       0.9917
p-value (slope)     :     6.47e-15
F-statistic         :      1553.89

==================================================
Regression Summary for: Master's Degree
==================================================
Intercept (β₀)   :    -42553.22
Slope (β₁)       :      0.01573
R²                 :       0.9696
p-value (slope)     :     3.00e-11
F-statistic         :       415.21

==================================================
Regression Summary for: Associate Degree
==================================================
Intercept (β₀)   :    -19501.87
Slope (β₁)       :      0.00782
R²                 :        0.949
p-value (slope)     :     8.87e-10
F-statistic         :       241.69

==================================================
Regression Summary for: Doctorate or Higher
==================================================
Intercept (β₀)   :     -8040.64
Slope (β₁)       :      0.00302
R²                 :       0.9247
p-value (slope)     :     1.12e-08
F-statistic         :       159.75

==================================================
Regression Summary for: High School
==================================================
Intercept (β₀)   :     -6685.04
Slope (β₁)       :      0.00437
R²                 :       0.8888
p-value (slope)     :     1.44e-07
F-statistic         :        103.9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafik listesi</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>plot_list <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (level <span class="cf">in</span> education_levels) {</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_regression, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Total Number of Enterprises</span><span class="st">`</span>, <span class="at">y =</span> .data[[level]])) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#08306B"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#EF3B2C"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Regression Analysis:"</span>, level),</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Total Number of Enterprises"</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"Number of R&amp;D Personnel"</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>  plot_list[[level]] <span class="ot">&lt;-</span> p</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 3+2 düzenleme (patchwork)</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>final_plot <span class="ot">&lt;-</span> </span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>  (plot_list[[<span class="dv">1</span>]] <span class="sc">+</span> plot_list[[<span class="dv">2</span>]] <span class="sc">+</span> plot_list[[<span class="dv">3</span>]]) <span class="sc">/</span> </span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>  (plot_list[[<span class="dv">4</span>]] <span class="sc">+</span> plot_list[[<span class="dv">5</span>]]) <span class="sc">+</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_layout</span>(<span class="at">guides =</span> <span class="st">"collect"</span>) <span class="sc">&amp;</span> </span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>, <span class="at">angle =</span> <span class="dv">30</span>),</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Göster</span></span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(final_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="model-summaries-and-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="model-summaries-and-interpretation">Model Summaries and Interpretation</h3>
<section id="bachelors-degree" class="level4">
<h4 class="anchored" data-anchor-id="bachelors-degree">Bachelor’s Degree</h4>
<ul>
<li><strong>Model</strong>: <em>Personnel = –233,577.20 + 0.07888 × Enterprises</em></li>
<li><strong>R² = 0.9917</strong>, indicating that 99.17% of the variation is explained by the model.</li>
<li><strong>p-value (slope) = 6.472e–15</strong>, which confirms high statistical significance.</li>
<li><strong>Interpretation</strong>: For every 1,000 new enterprises, the number of bachelor-level R&amp;D personnel increases by approximately 79 people.</li>
</ul>
</section>
<section id="masters-degree" class="level4">
<h4 class="anchored" data-anchor-id="masters-degree">Master’s Degree</h4>
<ul>
<li><strong>Model</strong>: <em>Personnel = –42,553.22 + 0.01573 × Enterprises</em></li>
<li><strong>R² = 0.9696</strong>, showing a strong model fit.</li>
<li><strong>p-value (slope) = 3.001e–11</strong></li>
<li><strong>Interpretation</strong>: A 1,000-unit increase in enterprises is associated with an increase of around 16 master’s-level personnel.</li>
</ul>
</section>
<section id="associate-degree" class="level4">
<h4 class="anchored" data-anchor-id="associate-degree">Associate Degree</h4>
<ul>
<li><strong>Model</strong>: <em>Personnel = –19,501.87 + 0.00782 × Enterprises</em></li>
<li><strong>R² = 0.9490</strong></li>
<li><strong>p-value (slope) = 8.872e–10</strong></li>
<li><strong>Interpretation</strong>: The number of associate-level personnel shows a strong and significant increase in parallel with enterprise growth.</li>
</ul>
</section>
<section id="doctorate-or-higher" class="level4">
<h4 class="anchored" data-anchor-id="doctorate-or-higher">Doctorate or Higher</h4>
<ul>
<li><strong>Model</strong>: <em>Personnel = –8,040.64 + 0.00302 × Enterprises</em></li>
<li><strong>R² = 0.9247</strong></li>
<li><strong>p-value (slope) = 1.119e–08</strong></li>
<li><strong>Interpretation</strong>: An increase of 1,000 enterprises results in approximately 3 additional doctorate-level R&amp;D personnel.</li>
</ul>
</section>
<section id="high-school" class="level4">
<h4 class="anchored" data-anchor-id="high-school">High School</h4>
<ul>
<li><strong>Model</strong>: <em>Personnel = –6,685.04 + 0.00437 × Enterprises</em></li>
<li><strong>R² = 0.8888</strong></li>
<li><strong>p-value (slope) = 1.441e–07</strong></li>
<li><strong>Interpretation</strong>: Although relatively lower than other education levels, the relationship remains positive and statistically significant.</li>
</ul>
</section>
</section>
<section id="general-assessment" class="level3">
<h3 class="anchored" data-anchor-id="general-assessment">General Assessment</h3>
<p>All models exhibit high R² values and statistically significant slope coefficients, indicating that the number of industrial enterprises is a strong predictor of R&amp;D personnel employment across all education levels. The strongest relationships are observed at the bachelor’s and master’s levels, while the high school and doctorate levels also show substantial, though relatively smaller, effects. These findings emphasize that industrial growth drives the demand for qualified human capital in the R&amp;D sector, highlighting the importance of aligning educational planning with industrial expansion.</p>
</section>
</section>
<section id="model-fitting" class="level2">
<h2 class="anchored" data-anchor-id="model-fitting">3.3 Model Fitting</h2>
<section id="multivariate-linear-regression-analysis" class="level3">
<h3 class="anchored" data-anchor-id="multivariate-linear-regression-analysis">Multivariate Linear Regression Analysis</h3>
<p>This section presents multivariate linear regression models to estimate the number of doctorate-level R&amp;D personnel in Turkiye between 2009 and 2023, using various explanatory variables such as total number of enterprises, gender distribution, and other education levels.</p>
<section id="base-model-enterprises-gender" class="level4">
<h4 class="anchored" data-anchor-id="base-model-enterprises-gender">Base Model: Enterprises + Gender</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Dosyaları oku</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>enterprises <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi-toplam girisim sayisi.xlsx"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>rd <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sanayi Hizmet Kuruluslari ArGe Faaliyetleri.xlsx"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Yılları tam sayıya çevir</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>enterprises<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(enterprises<span class="sc">$</span>Year)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>rd<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(rd<span class="sc">$</span>Year)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Yılları filtrele</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>enterprises <span class="ot">&lt;-</span> enterprises <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2009</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2023</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>rd <span class="ot">&lt;-</span> rd <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2009</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2023</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Eğitim düzeyine göre pivotla</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>education_data <span class="ot">&lt;-</span> rd <span class="sc">%&gt;%</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, <span class="st">`</span><span class="at">Education level</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Number =</span> <span class="fu">sum</span>(Number, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">`</span><span class="at">Education level</span><span class="st">`</span>, <span class="at">values_from =</span> Number)</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Cinsiyete göre pivotla</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>gender_data <span class="ot">&lt;-</span> rd <span class="sc">%&gt;%</span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Gender) <span class="sc">%&gt;%</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Number =</span> <span class="fu">sum</span>(Number, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Gender, <span class="at">values_from =</span> Number)</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Tüm veriyi birleştir</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>veri_model <span class="ot">&lt;-</span> enterprises <span class="sc">%&gt;%</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(education_data, <span class="at">by =</span> <span class="st">"Year"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(gender_data, <span class="at">by =</span> <span class="st">"Year"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Base model: Enterprises + Male + Female</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>model_temel <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">Doctorate or Higher</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">Total Number of Enterprises</span><span class="st">`</span> <span class="sc">+</span> Male <span class="sc">+</span> Female, <span class="at">data =</span> veri_model)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_temel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = `Doctorate or Higher` ~ `Total Number of Enterprises` + 
    Male + Female, data = veri_model)

Residuals:
    Min      1Q  Median      3Q     Max 
-407.45 -199.81  -24.95   89.87  689.49 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)                    3.428e+03  5.939e+03   0.577   0.5754  
`Total Number of Enterprises` -1.324e-03  1.937e-03  -0.684   0.5084  
Male                           8.882e-02  4.527e-02   1.962   0.0756 .
Female                        -7.792e-02  1.372e-01  -0.568   0.5814  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 323.6 on 11 degrees of freedom
Multiple R-squared:  0.9643,    Adjusted R-squared:  0.9545 
F-statistic: 98.96 on 3 and 11 DF,  p-value: 3.058e-08</code></pre>
</div>
</div>
</div>
<p><strong>Regression Equation:</strong></p>
<p><span class="math display">\[
\text{PhD} = 3428 - 0.00132 \cdot \text{Enterprises} + 0.0888 \cdot \text{Male} - 0.0779 \cdot \text{Female}
\]</span></p>
<p><strong>Interpretation of Coefficients:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 17%">
<col style="width: 11%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>3428</td>
<td>0.575</td>
<td>Not significant</td>
</tr>
<tr class="even">
<td>Total Enterprises</td>
<td>-0.00132</td>
<td>0.508</td>
<td>Not significant</td>
</tr>
<tr class="odd">
<td>Male</td>
<td>+0.0888</td>
<td>0.076</td>
<td>Marginally significant (p ≈ 0.0756)</td>
</tr>
<tr class="even">
<td>Female</td>
<td>-0.0779</td>
<td>0.0581</td>
<td>Not significant</td>
</tr>
</tbody>
</table>
<p><strong>Model Performance:</strong></p>
<ul>
<li><p><span class="math inline">\(R^2 = 0.9643\)</span></p></li>
<li><p>Adjusted <span class="math inline">\(R^2 = 0.9545\)</span></p></li>
<li><p>F-statistic = 98.96, p &lt; 0.001</p></li>
<li><p>Residual standard error = 323.6</p></li>
</ul>
<p>The multiple linear regression model is constructed to estimate the number of R&amp;D personnel at doctoral level. The number of industrial enterprises, number of male and female personnel are used as explanatory variables in the model. The overall fit of the model is quite strong (<span class="math inline">\(R^2 = 0.9643\)</span>) and most of the variance can be explained. However, when individual variables are analyzed, only the variable “number of male staff” is found to be borderline significant at the 10% significance level (<span class="math inline">\(p = 0.0756\)</span>). This result may indicate a multicollinearity problem due to the inclusion of the number of men and women in the model together.</p>
</section>
<section id="extended-model-education-levels-female-ratio" class="level4">
<h4 class="anchored" data-anchor-id="extended-model-education-levels-female-ratio">Extended Model: Education Levels + Female Ratio</h4>
<p>This model is constructed to analyze how the number of R&amp;D personnel at the PhD level is related to the number of industrial enterprises, the number of personnel at other levels of education and the share of women.</p>
<div class="cell">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>veri_model <span class="ot">&lt;-</span> veri_model <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Female_Ratio =</span> Female <span class="sc">/</span> (Female <span class="sc">+</span> Male))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extended model including education levels and female ratio</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>model_genis <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">Doctorate or Higher</span><span class="st">`</span> <span class="sc">~</span> </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">`</span><span class="at">Total Number of Enterprises</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                    <span class="st">`</span><span class="at">Master's Degree</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>                    <span class="st">`</span><span class="at">Bachelor's Degree</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>                    <span class="st">`</span><span class="at">Associate Degree</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>                    Other <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>                    Female_Ratio,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> veri_model)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_genis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = `Doctorate or Higher` ~ `Total Number of Enterprises` + 
    `Master's Degree` + `Bachelor's Degree` + `Associate Degree` + 
    Other + Female_Ratio, data = veri_model)

Residuals:
    Min      1Q  Median      3Q     Max 
-351.65 -103.67    6.41  142.64  280.30 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)                    8.832e+03  8.749e+03   1.010   0.3423  
`Total Number of Enterprises` -3.611e-03  1.919e-03  -1.882   0.0966 .
`Master's Degree`              5.107e-01  2.281e-01   2.239   0.0555 .
`Bachelor's Degree`            3.393e-02  2.437e-02   1.392   0.2013  
`Associate Degree`            -6.003e-01  2.956e-01  -2.031   0.0768 .
Other                          3.568e-03  6.697e-01   0.005   0.9959  
Female_Ratio                   1.401e+04  2.001e+04   0.700   0.5036  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 246.3 on 8 degrees of freedom
Multiple R-squared:  0.9849,    Adjusted R-squared:  0.9737 
F-statistic: 87.23 on 6 and 8 DF,  p-value: 7.522e-07</code></pre>
</div>
</div>
</div>
<p><strong>Regression Equation:</strong></p>
<p><span class="math display">\[\begin{multline*}
\text{PhD} = 8832 - 0.0036 \cdot \text{Enterprises} + 0.5107 \cdot \text{Master's} \\
+ 0.0339 \cdot \text{Bachelor's} - 0.6003 \cdot \text{Associate} \\
+ 0.0036 \cdot \text{Other} + 14014 \cdot \text{Female}
\end{multline*}\]</span></p>
<p><strong>Interpretation of Coefficients:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 22%">
<col style="width: 12%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient (β)</th>
<th>p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>8,832</td>
<td>0.342</td>
<td>Not significant</td>
</tr>
<tr class="even">
<td>Enterprises</td>
<td>–0.0036</td>
<td>0.0966</td>
<td>Marginally significant (10%)</td>
</tr>
<tr class="odd">
<td>Master’s Degree</td>
<td>+0.5107</td>
<td>0.0555</td>
<td>Marginally significant (5%)</td>
</tr>
<tr class="even">
<td>Bachelor’s Degree</td>
<td>+0.0339</td>
<td>0.201</td>
<td>Not significant</td>
</tr>
<tr class="odd">
<td>Associate Degree</td>
<td>–0.6003</td>
<td>0.0768</td>
<td>Marginally significant (10%)</td>
</tr>
<tr class="even">
<td>Other</td>
<td>+0.0036</td>
<td>0.996</td>
<td>Not significant</td>
</tr>
<tr class="odd">
<td>Female Ratio</td>
<td>+14,014</td>
<td>0.504</td>
<td>High effect size but NS</td>
</tr>
</tbody>
</table>
<p><strong>Model Performance:</strong></p>
<ul>
<li><span class="math inline">\(R^2 = 0.9849\)</span></li>
<li>Adjusted <span class="math inline">\(R^2 = 0.9737\)</span></li>
<li>F-statistic = 87.23, p &lt; 0.001</li>
<li>Residual standard error = 246.3</li>
</ul>
<p>This model analyzes the relationship between the number of PhD-level R&amp;D personnel and entrepreneurship and personnel structure. The model has a high explanatory power with an R² value of 98.5%. While master’s degree graduates have a positive and borderline significant effect, the effect of associate degree graduates is negative and borderline significant. Although the female ratio has a high effect coefficient, it is not statistically significant. This suggests that the interactions between education levels are determinant in the transition to doctoral level and that the gender effect is not direct.</p>
<p>Multivariate analysis confirms that PhD-level personnel are influenced more by internal structural factors such as the number of master’s degree holders, rather than external macro indicators like the total number of enterprises. To improve interpretability, future models could apply variance inflation factor (VIF) analysis or dimensionality reduction techniques to mitigate multicollinearity effects.</p>
</section>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">3.4 Results</h2>
<p>Two different multiple linear regression models were constructed in the analysis:</p>
<ul>
<li><p>Model 1: Basic model where the number of PhD-level employees is explained by the number of industrial enterprises and gender (male/female) distribution.</p></li>
<li><p>Model 2: Expanded model including education levels and the share of women.</p></li>
</ul>
<div class="cell">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gerekli dönüşümler ve eksik veri temizliği</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>veri_model <span class="ot">&lt;-</span> veri_model <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Female_Ratio =</span> Female <span class="sc">/</span> (Female <span class="sc">+</span> Male)) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Temel model (Model 1)</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>model_multi1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">Doctorate or Higher</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">Total Number of Enterprises</span><span class="st">`</span> <span class="sc">+</span> Female <span class="sc">+</span> Male, <span class="at">data =</span> veri_model)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Genişletilmiş model (Model 2)</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>model_multi2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">Doctorate or Higher</span><span class="st">`</span> <span class="sc">~</span> </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>                     <span class="st">`</span><span class="at">Total Number of Enterprises</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>                     <span class="st">`</span><span class="at">Master's Degree</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                     <span class="st">`</span><span class="at">Bachelor's Degree</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>                     <span class="st">`</span><span class="at">Associate Degree</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>                     Other <span class="sc">+</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>                     Female_Ratio,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> veri_model)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Performans karşılaştırma</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multi1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = `Doctorate or Higher` ~ `Total Number of Enterprises` + 
    Female + Male, data = veri_model)

Residuals:
    Min      1Q  Median      3Q     Max 
-407.45 -199.81  -24.95   89.87  689.49 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)                    3.428e+03  5.939e+03   0.577   0.5754  
`Total Number of Enterprises` -1.324e-03  1.937e-03  -0.684   0.5084  
Female                        -7.792e-02  1.372e-01  -0.568   0.5814  
Male                           8.882e-02  4.527e-02   1.962   0.0756 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 323.6 on 11 degrees of freedom
Multiple R-squared:  0.9643,    Adjusted R-squared:  0.9545 
F-statistic: 98.96 on 3 and 11 DF,  p-value: 3.058e-08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multi2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = `Doctorate or Higher` ~ `Total Number of Enterprises` + 
    `Master's Degree` + `Bachelor's Degree` + `Associate Degree` + 
    Other + Female_Ratio, data = veri_model)

Residuals:
    Min      1Q  Median      3Q     Max 
-351.65 -103.67    6.41  142.64  280.30 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)                    8.832e+03  8.749e+03   1.010   0.3423  
`Total Number of Enterprises` -3.611e-03  1.919e-03  -1.882   0.0966 .
`Master's Degree`              5.107e-01  2.281e-01   2.239   0.0555 .
`Bachelor's Degree`            3.393e-02  2.437e-02   1.392   0.2013  
`Associate Degree`            -6.003e-01  2.956e-01  -2.031   0.0768 .
Other                          3.568e-03  6.697e-01   0.005   0.9959  
Female_Ratio                   1.401e+04  2.001e+04   0.700   0.5036  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 246.3 on 8 degrees of freedom
Multiple R-squared:  0.9849,    Adjusted R-squared:  0.9737 
F-statistic: 87.23 on 6 and 8 DF,  p-value: 7.522e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC değerlerini karşılaştır</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model_multi1, model_multi2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             df      AIC
model_multi1  5 221.3032
model_multi2  8 214.3404</code></pre>
</div>
</div>
</div>
<table class="caption-top table">
<caption>Comparison of Regression Model Performance</caption>
<thead>
<tr class="header">
<th>Model</th>
<th><span class="math inline">\(R^2\)</span></th>
<th>Adjusted <span class="math inline">\(R^2\)</span></th>
<th>AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model 1</td>
<td>0.9643</td>
<td>0.9545</td>
<td>221.3032</td>
</tr>
<tr class="even">
<td>Model 2</td>
<td>0.9849</td>
<td>0.9737</td>
<td>214.3404</td>
</tr>
</tbody>
</table>
<p>As a result of the multiple linear regression analyses, it is observed that both models exhibit high performance in explaining the number of R&amp;D personnel at doctoral level. Model 1 is based on the number of industrial enterprises and gender variables and stands out as a strong base model with an R² value above 96%. However, Model 2 includes additional structural variables such as variables related to education (bachelor’s degree, master’s degree, associate’s degree, etc.) and the proportion of female employees; thus, it offers higher values in terms of both R² and Adjusted R², while also reaching a lower (i.e.&nbsp;more preferable) value in terms of the AIC criterion. This indicates that Model 2 is more explanatory not only because it includes more variables but also because these variables contribute significantly to the model.</p>
<p>The lower AIC value of Model 2 reveals that the estimates are more reliable in terms of generalizability. These results suggest that the R&amp;D staff structure at the PhD level should be evaluated not only with macro indicators such as the level of entrepreneurship or the total number of staff, but also with microstructural factors such as gender balance and education level. Therefore, it is recommended to prefer Model 2 in order to build more realistic, consistent and politically oriented models for strategic planning and decision-making processes.</p>
</section>
</section>
<section id="results-and-key-takeaways" class="level1">
<h1>4. Results and Key Takeaways</h1>
<p>This study analyzed the distribution of R&amp;D personnel working in the Turkish industrial sector according to their education levels using multiple linear regression models and revealed the determinants of the structure of PhD-level personnel. As a result of the comparison of two different models, the extended model (Model 2), which includes education-based variables and gender ratio, stands out with higher explanatory power and lower information loss. This suggests that R&amp;D personnel should be considered not only with macro indicators (e.g.&nbsp;number of enterprises) but also with micro structural factors (e.g.&nbsp;education level, gender ratio).</p>
<p>The model results show that especially master’s degree graduates have a decisive effect on the transition to PhD level. It is also noteworthy that PhD-level employment may be higher in institutional structures with a higher proportion of women. In light of these analyses, it is necessary to increase R&amp;D incentives at the doctoral level, develop interface policies to facilitate the integration of master’s degree graduates into the industry, define norms for qualified R&amp;D personnel per enterprise, and create structures to support the career transformation of bachelor’s degree graduates.</p>
<p>Overall, the findings suggest that the Turkish industry still relies on an undergraduate-based R&amp;D workforce structure, but this structure has limitations in terms of technological breakthrough and high value-added production. In this context, policies aimed at both increasing the quality of human capital and strengthening the structural interaction between industry and academia are critical for building sustainable R&amp;D capacity.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ul>
<li><p>Fox, J. (2015). <em>Applied regression analysis and generalized linear models</em> (3rd ed.). Sage Publications.</p></li>
<li><p>Hair, J. F., Black, W. C., Babin, B. J., &amp; Anderson, R. E. (2019). <em>Multivariate data analysis</em> (8th ed.). Cengage Learning.</p></li>
<li><p>Kutner, M. H., Nachtsheim, C. J., Neter, J., &amp; Li, W. (2005). <em>Applied linear statistical models</em> (5th ed.). McGraw-Hill/Irwin.</p></li>
<li><p>Montgomery, D. C., Peck, E. A., &amp; Vining, G. G. (2012). <em>Introduction to linear regression analysis</em> (5th ed.). Wiley.</p></li>
</ul>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Hacettepe IE - EMU660 - Spring 2025</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>